language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python setup.py test
before_install:
- openssl aes-256-cbc -K $encrypted_421408760930_key -iv $encrypted_421408760930_iv -in pyCMRConfig.cfg.enc -out pyCMRConfig.cfg -d
