language: python
python:
 - "2.7"

install:
   - "pip install -r requirements.txt"

script:
  - python setup.py test

notifications:
  email:
    on_success: never
    on_failure: never
  slack: ghrcdaac:7kcWm5tYC0eX9TiNGQ3jXQSl
    